
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mr_fix_it_development

test:
  <<: *default
  database: mr_fix_it_test

production:
  <<: *default
  database: mr_fix_it_production
  username: mr_fix_it
  password: <%= ENV['MR_FIX_IT_DATABASE_PASSWORD'] %>
